apiVersion: apps/v1
kind: Deployment
metadata:
  name: nashtech-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nashtech-application
  template:
    metadata:
      labels:
        app: nashtech-application
    spec:
      containers:
        - name: nashtech-application
          image: ghcr.io/deepak1067/myapp/myimage:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: nashtech-application-service
spec:
  selector:
    app: nashtech-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
